<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>06ffa13a-9bdc-442f-b071-c358daed3859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-6koalj.r-1777fci.r-1jkjb.r-bnwqim > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[4]/div/div/div/div/div/div/div/div/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/3/393c6a1dee81cd3dc84df59672d43edb.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>12</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-1jgb5lz r-xiad99 r-16k0tzm&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-1yos0t3 r-bztko3 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-6koalj r-18u37iz&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0 r-o8yidv r-1udh08x&quot;]/div[@class=&quot;css-1dbjc4n r-u8s1d r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0&quot;]/div[@class=&quot;css-1dbjc4n r-1loqt21 r-1otgn73 r-1x4r79x&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-855088 r-mm0ijv r-dwliz8 r-1loqt21 r-6koalj r-18u37iz r-ymttw5 r-5njf8e r-bnwqim r-14qw7yl r-1j63xyz r-lrvibr r-1x4r79x&quot;]/div[@class=&quot;css-1dbjc4n r-6koalj r-1777fci r-1jkjb r-bnwqim&quot;]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[4]/div/div/div/div/div/div/div/div/div/div[3]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://d1785e74lyxkqq.cloudfront.net/_next/static/v2/3/393c6a1dee81cd3dc84df59672d43edb.svg')])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[3]/img</value>
   </webElementXpaths>
</WebElementEntity>
